{
 "title": "Immich Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Estado de Contenedores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uso de CPU por contenedor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"container_name\"])\n  |> yield(name: \"CPU Usage\")"
    }
   ]
  },
  {
   "title": "Consumo de RAM por servicio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"container_name\"])\n  |> yield(name: \"RAM Usage\")"
    }
   ]
  },
  {
   "title": "Uso de CPU por contenedor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"container_name\"])\n  |> yield(name: \"CPU Usage\")"
    }
   ]
  },
  {
   "title": "Consumo de RAM por servicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"container_name\"])\n  |> yield(name: \"RAM Usage\")"
    }
   ]
  },
  {
   "title": "Tráfico de Red de entrada",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\")\n  |> derivative(unit: 1s, nonNegative: true) \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"container_name\"])\n  |> yield(name: \"Red Entrada (RX)\")"
    }
   ]
  },
  {
   "title": "Tráfico de Red de salida",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_bytes\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"container_name\"])\n  |> yield(name: \"Red Salida (TX)\")"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Conexiones Activas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"numbackends\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"db\"])\n  |> yield(name: \"Conexiones\")"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\n\nfrom(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blks_hit\" or r[\"_field\"] == \"blks_read\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      db: r.db,\n      _value: if (r.blks_hit + r.blks_read) > 0 then \n                (float(v: r.blks_hit) / float(v: r.blks_hit + r.blks_read)) * 100.0\n              else \n                0.0\n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"db\"])\n  |> yield(name: \"Hit Rate\")"
    }
   ]
  },
  {
   "title": "Transacciones por segundo (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"postgresql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"xact_commit\" or r[\"_field\"] == \"xact_rollback\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"db\"])\n  |> yield(name: \"TPS\")"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Operaciones por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"redis\")\n  |> filter(fn: (r) => r[\"_field\"] == \"instantaneous_ops_per_sec\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  // Limpiamos etiquetas para que se vea bonito\n  |> keep(columns: [\"_value\", \"_time\"]) \n  |> yield(name: \"Redis Ops\")"
    }
   ]
  },
  {
   "title": "Hits y Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"redis\")\n  |> filter(fn: (r) => r[\"_field\"] == \"keyspace_hits\" or r[\"_field\"] == \"keyspace_misses\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: \n        if r._field == \"keyspace_hits\" then \"Hits\" \n        else \"Misses\" \n  }))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n  |> yield(name: \"Ops\")"
    }
   ]
  },
  {
   "title": "Claves Evictadas",
   "type": "stat",
   "description": "Datos que ha tenido que borrar Redis porque se quedó sin RAM",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"redis\")\n  |> filter(fn: (r) => r[\"_field\"] == \"evicted_keys\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\"])\n  |> yield(name: \"Evicted\")"
    }
   ]
  },
  { "title": "Temperaturas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Temperatura CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_input\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"sensor\"])\n  |> yield(name: \"Temperatura\")"
    }
   ]
  },
  {
   "title": "Temperatura CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"immich\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_input\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> mean()                   \n  |> yield(name: \"Temperatura CPU\")"
    }
   ]
  },
  { "title": "LOGS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Logs: Immich Server",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"immich_server\"}"
    }
   ]
  },
  {
   "title": "Errores 🚨: immich_server",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"immich_server\"} |= \"error\""
    }
   ]
  },
  {
   "title": "Logs: PostgreSQL",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"immich_postgres\"}"
    }
   ]
  },
  {
   "title": "Logs: Redis",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"immich_redis\"}"
    }
   ]
  },
  {
   "title": "Logs: immich_machine_learning",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"immich_machine_learning\"}"
    }
   ]
  }
 ]
}